POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username" : "user4",
    "password" : "user4"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username" : "user1",
    "password" : "user1"
}

###
POST http://localhost:5000/api/playlist
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWE3YWYzODY5M2VjMDMzNjJiYzkyMmQiLCJpYXQiOjE2Mzg3MTIwOTd9.esqevk6e-BHSXZR-mXaoxF9XLp-x9fWgP62YbO96lqQ

{
    "name" : "VU",
    "src" : "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Vu_monsoon2019.jpg/1200px-Vu_monsoon2019.jpg"
    
}


###
PUT http://localhost:5000/api/playlist/61acc14d764e608443ef633b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWE3YWYzODY5M2VjMDMzNjJiYzkyMmQiLCJpYXQiOjE2Mzg3MTIwOTd9.esqevk6e-BHSXZR-mXaoxF9XLp-x9fWgP62YbO96lqQ
{
    "title" : "Update",
    "thumbnail" : "weqasdasdqweqw"
}




###
GET http://localhost:5000/api/playlist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWE3YWYzODY5M2VjMDMzNjJiYzkyMmQiLCJpYXQiOjE2Mzg3MTIwOTd9.esqevk6e-BHSXZR-mXaoxF9XLp-x9fWgP62YbO96lqQ
